language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
script:
- cmake .
- cmake --build .
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uromalxr:$BINTRAY_API_KEY "https://api.bintray.com/content/romalxr/otus/lessons/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"